### ISSUE TITLE
Comments on Abstract

### ISSUE THREAD

**Issue by evansuva** [michwill/zerodb-whitepaper#1]
I think you're committed to the name "ZeroDB", but important to be clear that the "Zero" is not what is typically meant in cryptography where it alludes to "Zero Knowledge" (with a strong indistinguishably definition behind this). The ZeroDB system doesn't approach the requirements for Zero Knowledge since there is plenty of information leaked through the access patterns, even if the data is still encrypted.

"Since the server has no insight into the nature of the data, the risk of a server-side data
breach is eliminated. Even if adversaries successfully infiltrate the server, they will not have access
to the cleartext data."

There are lots of potentially damaging things an attacker who compromises the server side could do even if the data is encrypted.  It could ignore updates, send bogus responses, etc.  Okay to ignore these issues, since eliminating the risk of the data being exposed is a good focus, but should be clear if these are in/out of scope.

**Comment by michwill** [comment]
[Specified](https://github.com/michwill/zerodb-whitepaper/commit/dc6c2f89178a85106f8427f10f5acad5182a1cda) passive adversaries in the abstract, pointing out that we look at snapshot-level data leak
