### ISSUE TITLE
Introduction Comments

### ISSUE THREAD

**Issue by evansuva** [michwill/zerodb-whitepaper#2]
"These techniques typically fall into two broad categories: ..."  

I'm somewhat biased because of my own research interests, but I would put multi-party computation approaches as a third broad category here (or could be sub-category of compute on encrypted data). Substantially different from either FHE or PHE, but also requires a different interaction model.

Would be good to clarify in the introduction the threat model you have in mind and operation scenario.  I think you are assuming a single client that initially has all the data, and wants to outsource it to an untrusted server, keeping just a small and constant amount of storage on the client.  (I see Section III will get into multiple users.)

**Comment by mswilkison** [comment]
Addressed here: https://github.com/michwill/zerodb-whitepaper/commit/997462bc5b6899919c2e154f6665c77d6d36a910

and here: https://github.com/michwill/zerodb-whitepaper/commit/9bec40ab96705ea7be6340c7c0c2dce75cdf3277
