### ISSUE TITLE
Query Protocol

### ISSUE THREAD

**Issue by evansuva** [michwill/zerodb-whitepaper#3]
"The server is responsible for ... user authentication"
So, does this mean the server can collude with the lowest-access privilege user to gain full access to all the data?  Would be better if user authentication is done cryptographically (e.g., through key management and encryption of records), so it is not necessary to rely on the untrusted server to do this.

"When data are organized in B-Trees, doing range queries is easy."
The problem with any organization like this, is it contradicts the earlier claim that "As a result,
the server does not know how individual objects are organized within the B-Tree or whether they even belong to an index at all."  Any way of organizing the data base on its semantic values, risks leaking a lot of information to the server.  For the example in Fig 3, for example, any query that goes down the left side of the tree reveals to the server that it is looking for low-valued objects.  After a few queries like this, and with any outside knowledge about the type of data being stored, the server quickly has a lot of information about the actual data.

C. Complex Queries
This is written like it doesn't matter if the query itself is (mostly) leaked.  Is that the intent?  There needs to be a clearer statement of the privacy properties the system is designed for.  I would think query privacy is important for many uses, but the optimizations here reveal a lot of information about the query.

**Comment by michwill** [comment]
1. If the server colludes with the lowest-privilege user (if that is organized via proxy re-encryption or sharing of a trees of derived keys), it would be able to get access to the same data as that user has an access to. If a compromised server returns the data user shouldn't have access to, he wouldn't be able to decrypt that anyway. But of course, read quotas, if exist, are not cryptographically secured.
2. Links between nodes of the B-Tree are visible only to the client b/c these links are parts of the encrypted nodes. The server can quickly deduce which level of a B-Tree an object could belong to though (e.g. root, level 1 etc). The server cannot see if a related object is located left or right. Will clarify this point as well.
3. I think, I'll remove this (Complex queries) section, replacing with iterative fulltext search which doesn't require these compromises. And we'll not implement this approach
