### ISSUE TITLE
Sharing Data

### ISSUE THREAD

**Issue by evansuva** [michwill/zerodb-whitepaper#4]
I think the multiple user case is really the only case that matters for this model.  Storage is super cheap - <$100 for a TB, and even cheap mobile devices have hundreds of GB available (or more on a cheap SD card, etc.).  So, if someone has sensitive data they need regular access to, there is little justification for not just storing it themselves.  After this, the cloud offers reliable backup, etc., but simple enough to just do client-side encryption of the whole data store and use the cloud just as a backup that can be used to restore the whole database, with all the database operations done locally.

The desire for encrypted outsourced databases, only makes a lot of sense to me if multiple users can be handled well, including with updates.

I haven't yet gone through this section enough to be convinced if the proposed solution is a good one, but I think its important to emphasize the multiple user scenario early in the presentation.

**Comment by michwill** [comment]
One usecase we see appearing often for this is giving a temporary (even only read) permission to an external user. If that user leaks the temporary key afterwards, that shouldn't be a problem. But yeah, we'll emphasize that this is for multi-user scenario.

**Comment by michwill** [comment]
Added some usecases for sharing. But will leave the issue open for now (maybe can add more)
