### ISSUE TITLE
Security Analysis

### ISSUE THREAD

**Issue by evansuva** [michwill/zerodb-whitepaper#5]
"We assume that both strong and weak adversaries are passive" - the passive assumption is a very strong (and unrealistic for your scenarios) one, so I would say that both the "strong" and "weak" adversaries are "weak" (that is, they only have the power to observe).  The standard honest-but-curious model assumes that adversary has access to a full transcript of the protocol execution, so no distinction made between your "strong" and "weak" adversaries.  I don't really understand the motivation for the "weak" adversary - why wouldn't the web adversary be able to store the snapshots they make over time to become equivalent to a "strong" adversary?

The other question about the adversary is what pre-knowledge they might have access to - e.g., do they know anything about the data being stored or the typical distribution of queries and responses?

"In ZeroDB, all contents of the database and indexes are stored as encrypted objects. Therefore, a weak adversary does not learn anything except for database size (including the number of fields, etc), even during queries. So, ZeroDB provides semantic security against a weak adversary."
To make this convincing, you would need to show that the observable pattern for each query is indistinguishable. I don't think that is the case, but may not understand the B-tree protocol well enough.  But, with your definition of a weak adversary maybe it is trivially satisfied - but it is such a weak adversary to make the claim meaningless if you really mean it just sees the encrypted state once and nothing else.  (I thought you are assuming an untrusted server and trying to show security properties against an untrusted server?)

"An active adversary is able to acquire access statistics" - don't think you mean "active" adversary here, just a fully capable passive one.  

"The fraction of last names which can be revealed by a strong adversary
from a query given some number of queries is shown on..."
I think you are making strong assumptions about the structure of the B-tree not revealing anything.  This could be the case if it is organized randomly; but, then the queries are no longer possible. I don't see anyway to organize the B-tree that wouldn't leak information to the server, without requiring a lot of extra state on the client.

"Several algorithms are available, though the most promising ones are Burst
ORAM [10] and oblivious data structures [12]." - Some much better ones available now (including one from our group (that will be available soon).  Lots of interesting possible designs that combine ORAMs with B-tree-like database structures.

**Comment by michwill** [comment]
We used the same definitions as in Microsoft's CipherBase paper. We can use more precise definitions. Both kinds of adversaries are passive, one can indeed see a snapshot of anything, another can observe these snapshots changing over time. Probably, we can call them "instant" and "resident" adversaries to describe them in one word more precisely.

Adversaries do not necessarily know which indexes do data belong to, etc. But let's assume the worst for simplicity - that they know exactly what data are stored and which blocks belong to index.

Regarding organization of a B-Tree - as I said, the links between the nodes are only visible to the client (and we need to clarify that). The server can figure out which of the nodes are the leaf nodes, but this doesn't give as much useful information as statistics of accesses of objects or these leaf nodes.

That's really good that new research is coming with regards to ORAM! We've been told that a very good group to watch here is that of [Elaine Shi](http://elaineshi.com/publications.html)
